microsoft/OSSGadget

- src/oss-health/HealthMetrics.cs
Added ascii bars to the health report printout.
I'm sure there are probably better ways to do this, it's been a while.
> Now with ascii bars

- Pipelines/core-pipeline.yml
Adds 'Build Test' stage to pipeline
> Add Build Tests to Pipeline

- Dockerfile
- README.md
This change allows us to create a docker image with OSSGadget, build the source code, and use binaries in the docker container. That helps to create a local development environment quickly or use that without having the C# IDE/Env installed.
```
→ docker build -t ossgadget:latest .
→ docker run -it ossgadget:latest /bin/bash
root@f70569fe5456:/app/src# ./oss-download/bin/Debug/netcoreapp3.1/oss-download 
Microsoft OSS Gadget - oss-download 0.1.0.0
No target provided; nothing to download.
oss-download 0.1.0.0
Usage: oss-download [options] package-url...
positional arguments:
package-url                 PackgeURL specifier to download (required, repeats OK)
The package-url specifier is described at https://github.com/package-url/purl-spec:
pkg:cargo/rand                The latest version of …
```
> Add Dockerfile to run OSSGadget in the container

- Pipelines/core-pipeline.yml
> Pipeline Fixes: Update nuget/restore tasks, Switch to .NET Test Utility

- src/MultiExtractor/Extractor.cs
- src/MultiExtractor/Shared.MultiExtractor.csproj
- src/tests/tests.csproj
> Add more Disc formats from DiscUtils

- src/MultiExtractor/Extractor.cs
Combine parallel and single threaded into single functions.
Paralellize Ar, Deb and Wim extraction.
> Parallelization Cleanup

- src/MultiExtractor/Extractor.cs
- src/Shared/Shared.csproj
> Fix Premature Dispose in extractors using DumpLogicalVolumes

- Pipelines/core-pipeline.yml
- src/MultiExtractor/Shared.MultiExtractor.csproj
- src/OSSGadget.sln
- src/tests/ExtractorTests.cs
Adds packaging and signing MultiExtractor. 
Disables vhdx extraction tests
Removes 'tests' from Release configuration
Closes #47
> Add MultiExtractor NuGet Packaging

- Pipelines/recursiveextractor-pipeline.yml
- src/RecursiveExtractor.Tests/ExtractorTests.cs
- src/RecursiveExtractor.Tests/RecursiveExtractor.Tests.csproj
> Enable zbxl.zip

- src/CryptoGatherer/CodeSnippet.cs
- src/CryptoGatherer/Form1.cs
And use those functions in the gatherer.
> Add a ToString and FromString function to CodeSnippet

- src/Shared/PackageManagers/CocoapodsProjectManager.cs
- src/oss-characteristics/CharacteristicTool.cs
- src/oss-detect-backdoor/DetectBackdoorTool.cs
- src/oss-download/DownloadTool.cs
- src/oss-risk-calculator/RiskCalculatorTool.cs
2) Change the downloadDirectory to a non nullable class member (to avoid crashes with the commandlineparser
3) Move download tool and characterstic tool to the command line parser
> 1) Remove folder deletion code from oss-downloader

- src/RecursiveExtractor/RecursiveExtractor/FileEntry.cs
Add Support for passing constructing a FileEntry from an asynchronous stream.
> Support Asynchronous Streams

- Pipelines/templates/sdl-job.yml
- src/Shared/Helpers/PackageDownloader.cs
- src/Shared/PackageManagers/BaseProjectManager.cs
- src/Shared/PackageManagers/NuGetProjectManager.cs
- src/Shared/PackageManagers/UbuntuProjectManager.cs
- src/Shared/Shared.csproj
- src/Shared/nlog.config
- src/oss-characteristics/CharacteristicTool.cs
- src/oss-characteristics/oss-characteristic.csproj
- src/oss-defog/oss-defog.csproj
- src/oss-detect-backdoor/oss-detect-backdoor.csproj
- src/oss-detect-cryptography/oss-detect-cryptography.csproj
- src/oss-download/oss-download.csproj
- src/oss-find-source/oss-find-source.csproj
- src/oss-health/oss-health.csproj
- src/oss-risk-calculator/RiskCalculatorTool.cs
- src/oss-risk-calculator/oss-risk-calculator.csproj
- src/oss-tests/DownloadTests.cs
- src/oss-tests/oss-tests.csproj
This PR contains minor fixes to a few different areas, but the most significant is an updated risk calculation algorithm.
> Update dependencies, risk calculator algorithm

- Pipelines/core-pipeline.yml
- Pipelines/templates/dotnet-publish-linux-mac-job.yml
- Pipelines/templates/dotnet-publish-win-netcore-job.yml
- Pipelines/templates/dotnet-test-job.yml
- Pipelines/templates/nuget-build-job.yml
- src/Shared/Shared.csproj
- src/oss-characteristics/oss-characteristic.csproj
- src/oss-defog/oss-defog.csproj
- src/oss-detect-backdoor/oss-detect-backdoor.csproj
- src/oss-detect-cryptography/oss-detect-cryptography.csproj
- src/oss-download/oss-download.csproj
- src/oss-find-source/oss-find-source.csproj
- src/oss-health/oss-health.csproj
- src/oss-risk-calculator/oss-risk-calculator.csproj
- src/oss-tests/oss-tests.csproj
> Retarget all projects to .net 5.0 rc

- src/oss-detect-cryptography/DetectCryptographyTool.cs
This PR fixes a few potential null dereferences.
> Fix nullable warning.

- .github/workflows/codeql-analysis.yml
- Directory.Build.props
- src/Shared/Shared.csproj
- src/oss-characteristics/oss-characteristic.csproj
- src/oss-defog/oss-defog.csproj
- src/oss-detect-backdoor/oss-detect-backdoor.csproj
- src/oss-detect-cryptography/oss-detect-cryptography.csproj
- src/oss-download/oss-download.csproj
- src/oss-find-source/oss-find-source.csproj
- src/oss-health/oss-health.csproj
- src/oss-risk-calculator/oss-risk-calculator.csproj
- src/oss-tests/oss-tests.csproj
- version.json
Update CodeQL Action with a step to install the .NET 5 SDK
> Update CodeQL Action with .NET 5

- src/Shared/PackageManagers/VSMProjectManager.cs
> Leave VSM stream open (fixes #173)

- src/Shared/Shared.csproj
- src/oss-characteristics/oss-characteristic.csproj
- src/oss-defog/oss-defog.csproj
- src/oss-detect-backdoor/oss-detect-backdoor.csproj
- src/oss-detect-cryptography/oss-detect-cryptography.csproj
- src/oss-download/oss-download.csproj
- src/oss-find-source/oss-find-source.csproj
- src/oss-health/oss-health.csproj
- src/oss-risk-calculator/oss-risk-calculator.csproj
- src/oss-tests/oss-tests.csproj
> Bump Dependencies

- src/Shared/CommonInitialization.cs
- src/Shared/PackageManagers/NuGetProjectManager.cs
- src/oss-download/DownloadTool.cs
- src/oss-tests/DownloadTests.cs
This change updates the NuGet manager to dynamically find the right endpoint, which should fix some missing packages, as well as minor fixes to a few other files.
> Fix #179 (dynamic NuGet API endpoints)

- src/Shared/CommonInitialization.cs
- src/Shared/PackageManagers/NuGetProjectManager.cs
- src/oss-download/DownloadTool.cs
- src/oss-tests/DownloadTests.cs
* Remove extra stack trace.
* Update NuGet endpoint (dynamic), Add auto gzip.
* Return RegistrationEndpoint instead.
* Switch cast to 'as'
> Fix #179 (dynamic NuGet API endpoints) (#182)

- src/oss-find-squats/FindSquatsTool.cs
- src/oss-find-squats/Generative.cs
> Fixes 193 and 192

- src/OSSGadget.sln
- src/Shared/Helpers/OutputBuilder/StringOutputBuilder.cs
- src/Shared/PackageManagers/NPMProjectManager.cs
- src/Shared/PackageManagers/PyPIProjectManager.cs
- src/Shared/PackageManagers/URLProjectManager.cs
- src/Shared/PackageManagers/VSMProjectManager.cs
- src/oss-diff/Diff.cs
- src/oss-diff/DiffTool.cs
- src/oss-diff/oss-diff.csproj
Adds the oss-diff tool for diffing packages.  Respects NO_COLOR. Has arguments for Before lines After lines and Overall Context, Output Format and Crawling Archives.
> Add oss-diff

- src/oss-find-squats/FindSquatsTool.cs
- src/oss-find-squats/Generative.cs
- src/oss-tests/FindSquatsTests.cs
Adds Bit Flips, Missed Characters, Vowel Swap and Double Hit (hitting a close character when typing an intentional letter)
Fix #205.
> Add more Typo-Squat generators

- src/oss-characteristics/CharacteristicTool.cs
Temporary AppInspector Workaround
> Disable Multithreading App Inspector

- src/oss-find-squats/Generative.cs
In addition to https://github.com/microsoft/OSSGadget/pull/221.
> Fix few more typos (Homoglphs -> Homoglyphs, chanaged -> changed)

- src/oss-detect-backdoor/Resources/BackdoorRules/backdoor_signatures.json
- src/oss-detect-backdoor/Resources/BackdoorRules/code_execution.json
- src/oss-detect-backdoor/Resources/BackdoorRules/obfuscation.json
This PR will be used for a bunch of new backdoor detection rules.
> Add a few additional rules.

- src/oss-detect-backdoor/Resources/BackdoorRules/dependency_confusion.json
- src/oss-detect-backdoor/Resources/BackdoorRules/ioc.json
- src/oss-detect-backdoor/Resources/BackdoorRules/reverse_shell.json
We had a few broken backdoor detection rules. This PR fixes them.
> Fix a few broken rules.

- src/oss-characteristics/CharacteristicTool.cs
- src/oss-detect-backdoor/DetectBackdoorTool.cs
- src/oss-detect-backdoor/Resources/BackdoorRules/dependency_confusion.json
- src/oss-health/HealthTool.cs
- src/oss-reproducible/ReproducibleTool.cs
This PR adds a few backdoor rules and does some minor output cleanup
> Backdoor Rules / Output Cleanup

- Pipelines/core-pipeline.yml
- Pipelines/templates/check-changes.yml
- src/Shared/PackageManagers/BaseProjectManager.cs
- src/Shared/PackageManagers/GitHubProjectManager.cs
- src/Shared/PackageManagers/NPMProjectManager.cs
- src/Shared/PackageManagers/PyPIProjectManager.cs
- src/oss-find-squats-lib/FindPackageSquatResult.cs
- src/oss-find-squats-lib/MutateExtension.cs
- src/oss-find-squats-lib/MutateOptions.cs
- src/oss-find-squats/oss-find-squats.csproj
Also some additional comments.
This should properly trigger the publication of the shared lib.
> Fix Check-Changes.yml

- src/oss-download/DownloadTool.cs
> Fix --help on download tool.

- src/oss-find-squats-lib/Mutators/RemovedCharacterMutator.cs
- src/oss-tests/FindSquatsTests.cs
It wasn't removing the first character in the string.
Also added a test to check for that case.
> Found a bug in RemovedCharacterMutator

- Pipelines/core-pipeline.yml
> Should fix version mismatches on nuget

- src/Shared/Shared.Lib.csproj
Change the version of Microsoft.Extensions.Caching.Memory to the non-preview version of 6.0.0
> Update Microsoft.Extensions.Caching.Memory version to 6.0.0

- src/Shared/PackageActions/NuGetPackageActions.cs
- src/Shared/PackageManagers/TypedManager.cs
- src/oss-tests/DownloadTests.cs
> Fix wildcard version NuGet downloads.

- src/oss-detect-backdoor/DetectBackdoorTool.cs
- src/oss-detect-backdoor/Resources/BackdoorRules/obfuscation.json
This PR adds checks for a few strings that have been found in PoC backdoors.
> Add backdooor check for obfuscated system commands (python)

- NOTICE.txt
This PR updates our NOTICE.txt file with the latest updates.
> Update NOTICE.txt file with latest dependencies.

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/tasks.json
This PR adds a few files which helps developers work on OSS Gadget via Codespaces.
> Initial import of Codespaces config.

- src/Shared/PackageManagers/BaseProjectManager.cs
- src/oss-tests/ProjectManagerTests/NPMProjectManagerTests.cs
Just added a method to BaseProjectManager.cs to check and see if a version of a package exists.
> Add a method to assert that a package version exists.

- src/Shared/PackageManagers/NuGetProjectManager.cs
- src/oss-tests/ProjectManagerTests/NuGetProjectManagerTests.cs
`NuGetProjectManager.GetArtifactDownloadUris` now:
* Handles uppercase characters in version strings properly (by lowercasing them according to [spec](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#download-package-content-nupkg))
* Tolerates the `Qualifiers` field on a given `PackageURL` being non-null, but empty
* Throws `NotImplementedException` instead of returning a bogus URL for package versions with a `repository_url` other than that of nuget.org
* Executes eagerly, instead of lazily / upon `IEnumerable` enumeration. (When `yield` statements are present, C# apparently defers execution of the whole method until the return value is enumerated. This can make stack traces harder to follow, when exceptions that one might expect to be thrown at the time of …
> Fix a few problems with NuGetProjectManager.GetArtifactDownloadUris

- src/Shared/PackageManagers/NPMProjectManager.cs
- src/Shared/PackageManagers/NuGetProjectManager.cs
- src/Shared/PackageManagers/PyPIProjectManager.cs
- src/Shared/PackageManagers/TypedManager.cs
- src/oss-tests/ProjectManagerTests/NPMProjectManagerTests.cs
- src/oss-tests/ProjectManagerTests/PyPIProjectManagerTests.cs
Implement for Npm and PyPI. Can't figure out NuGet easily so it just throws a NotImplementedException.
> Add GetPackagesFromOwnerAsync for the TypedManager.

- src/Shared/Helpers/EnvironmentHelper.cs
- src/Shared/PackageManagers/CPANProjectManager.cs
- src/Shared/PackageManagers/CRANProjectManager.cs
- src/Shared/PackageManagers/CargoProjectManager.cs
- src/Shared/PackageManagers/CocoapodsProjectManager.cs
- src/Shared/PackageManagers/ComposerProjectManager.cs
- src/Shared/PackageManagers/GemProjectManager.cs
- src/Shared/PackageManagers/GitHubProjectManager.cs
- src/Shared/PackageManagers/GolangProjectManager.cs
- src/Shared/PackageManagers/HackageProjectManager.cs
- src/Shared/PackageManagers/MavenProjectManager.cs
- src/Shared/PackageManagers/NPMProjectManager.cs
- src/Shared/PackageManagers/NuGetProjectManager.cs
- src/Shared/PackageManagers/PyPIProjectManager.cs
- src/Shared/PackageManagers/UbuntuProjectManager.cs
- src/Shared/PackageManagers/VSMProjectManager.cs
- src/oss-tests/Helpers/FindSquatsHelper.cs
Update Environment helper to match only modifying public statics
> Change Environment Variables to be non-static + public

- src/oss-detect-backdoor/Resources/BackdoorRules/code_execution.json
- src/oss-detect-backdoor/Resources/BackdoorRules/dependency_confusion.json
- src/oss-detect-cryptography/DetectCryptographyTool.cs
- src/oss-detect-cryptography/Resources/CryptographyRules/reference-common.json
- src/oss-tests/DetectCryptographyTests.cs
- src/oss-tests/DownloadTests.cs
> Fixes App Inspector Rules

- src/Shared/PackageManagers/CondaProjectManager.cs
- src/Shared/PackageManagers/ProjectManagerFactory.cs
- src/oss-tests/ProjectManagerTests/CondaProjectManagerTests.cs
We only need check for package existence at this point, but I'm also adding the package download code as part of this change.
> Add basic support for Conda

- src/oss-detect-backdoor/Resources/BackdoorRules/backdoor_signatures.json
- src/oss-detect-backdoor/Resources/BackdoorRules/code_execution.json
- src/oss-detect-backdoor/Resources/BackdoorRules/obfuscation.json
- src/oss-detect-backdoor/Resources/BackdoorRules/pastebin.json
> Adds more detections

- src/Shared/PackageManagers/PyPIProjectManager.cs
> Revert change for possible location properties

- src/Shared/PackageManagers/MavenProjectManager.cs
- src/oss-tests/ProjectManagerTests/MavenProjectManagerTests.cs
- src/oss-tests/Properties/Resources.Designer.cs
- src/oss-tests/Properties/Resources.resx
- src/oss-tests/TestData/Maven/maven_fluentui_listitem_0.0.8.pom
- src/oss-tests/TestData/Maven/maven_microsoft_fluentui_listitem_0.0.8.html
- src/oss-tests/TestData/Maven/maven_microsoft_fluentui_listitem_all.html
- src/oss-tests/TestData/Maven/maven_microsoft_fluentui_listitem_metadata.xml
Added tests for it, and tests for EnumerateVersions in Maven.
> Fix issues with PackageVersionExistsAsync for Maven.

- README.md
> Update README.md to note OSS-Reproducible

- src/oss-detect-backdoor/DetectBackdoorTool.cs
Add line number for excerpt in oss-detect-backdoor (resolves  #449 )
> Add line number for excerpt in oss-detect-backdoor

- .github/workflows/codeql-analysis.yml
- Pipelines/core-pipeline.yml
- Pipelines/templates/dotnet-test-job.yml
- Pipelines/templates/nuget-build-job.yml
- Pipelines/templates/sdl-job.yml
Also update github codeql workflow to include net 6 and 8.
> Update Pipeline Pools

- src/Shared/PackageManagers/CargoProjectManager.cs
- src/oss-tests/ProjectManagerTests/CargoProjectManagerTests.cs
- src/oss-tests/ProjectManagerTests/GolangProjectManagerTests.cs
- src/oss-tests/SkipInADOFact.cs
- fix test by having PackageVersionExistsAsync respect use useCache
- add custom attribute to conditionally skip tests in CI
> fix failing Cargo PackageVersionExistsAsync test
