Pipelines/core-pipeline.yml
Change windows to generic x64 target, re-enable linux, mac, netcoreapp
Fixes #19
=> Update pipeline to re-enable multiple platform targets

src/OSSGadget.sln, src/Shared/MultiExtractor/ArArchiveFile.cs, src/Shared/MultiExtractor/Extractor.cs, src/Shared/MultiExtractor/MiniMagic.cs, src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/UbuntuProjectManager.cs, src/Shared/PackageUrl/PackageUrl.cs, src/Shared/nlog.config, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-detect-cryptography/Resources/CryptographyRules/implementation-asymmetric.json, src/oss-detect-cryptography/Resources/CryptographyRules/implementation-block-cipher.json, src/oss-detect-cryptography/Resources/CryptographyRules/implementation-crypto-generic.json, src/oss-detect-cryptography/Resources/CryptographyRules/implementation-hash.json, src/oss-detect-cryptography/Resources/CryptographyRules/implementation-prng.json, src/oss-detect-cryptography/Resources/CryptographyRules/implementation-signature.json, src/oss-detect-cryptography/Resources/CryptographyRules/implementation-symmetric.json, src/oss-detect-cryptography/oss-detect-cryptography.csproj, src/oss-download/DownloadTool.cs, src/oss-download/oss-download.csproj, src/tests/tests.csproj
This pull requests includes a basic tool for detecting cryptographic implementations, meaning, code that does the math behind the crypto, not code that just *uses* crypto. (For that, use oss-characteristic.)
It does this with a combination of pattern matching (magic strings), searching package metadata, and decompiling .NET and native binaries, in an attempt to find those same magic strings.
The tool also implements a PackageManager for Ubuntu, and adds support for .deb files to MultiExtractor.
=> Add cryptographic implementation detection

src/MultiExtractor/Extractor.cs, src/MultiExtractor/FileEntry.cs, src/MultiExtractor/MiniMagic.cs
Discovered an issue with this when creating new benchmarks for Application Inspector https://github.com/microsoft/ApplicationInspector/pull/215 and porting the fix to the official multi-extractor here.
=> Use ConcurrentStack instead of List for thread safety

src/MultiExtractor/Extractor.cs, src/MultiExtractor/ExtractorOptions.cs
Also switch to having an Options class, and the extractor constructor takes an Options instance.
=> Add Option to not return original file on failed extraction

src/RecursiveExtractor/RecursiveExtractor.Tests/ExtractorTests.cs, src/RecursiveExtractor/RecursiveExtractor.Tests/RecursiveExtractor.Tests.csproj, src/RecursiveExtractor/RecursiveExtractor.Tests/TestData/TextFile.md, src/RecursiveExtractor/RecursiveExtractor/Extractor.cs, src/RecursiveExtractor/RecursiveExtractor/FileEntry.cs
Copies the raw file into a new FileEntry not reusing original stream which we can't rely on.
Add single file extraction test
=> Fix raw file extraction

src/Shared/PackageManagers/GitHubProjectManager.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/oss-characteristics/CharacteristicTool.cs, src/oss-tests/DetectCryptographyTests.cs, src/oss-tests/DownloadTests.cs, src/oss-tests/FindSourceTests.cs, src/oss-tests/VersionTests.cs
This PR adds initialization to each of the test classes so that the HttpClient will be initialized before use.
It also improves the regular expression used to extract GitHub URLs, which was referenced in #153.
=> Fixes #155 (missing HttpClient init), GitHub find source regex #153, #156, .NET Core 5 merge.

src/oss-detect-backdoor/DetectBackdoorTool.cs, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-tests/DownloadTests.cs
This PR fixes a few brittle test cases and improves portability of the backdoor rules on Linux. It also takes care of a few nullability warnings -- we have more to clean up though.
=> Fix tests, backdoor rules on Linux

src/OSSGadget.sln, src/Shared/Model/PackageMetadata.cs, src/Shared/Model/Repository.cs, src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/Shared/Shared.csproj, src/Shared/Utilities/Utilities.cs, src/oss-characteristics/oss-characteristic.csproj, src/oss-defog/oss-defog.csproj, src/oss-detect-backdoor/oss-detect-backdoor.csproj, src/oss-detect-cryptography/oss-detect-cryptography.csproj, src/oss-find-source/oss-find-source.csproj, src/oss-health/oss-health.csproj, src/oss-metadata/MetadataTool.cs, src/oss-metadata/oss-metadata.csproj, src/oss-risk-calculator/oss-risk-calculator.csproj, src/oss-tests/FindSourceTests.cs
This is the initial commit PR for the oss-metadata tool, and the common package metadata schema. The common package metadata schema is an effort to represent any package (npm, pypi, nuget, etc), in a common schema, so that they can be analyzed and stored according to a common set of rules. 
Much like how PURL combines different package urls into one unified schema, metadata tool tries to combine most of the package metadata into a common JSON schema. The changes in this PR are:
1) Proposal for a common schema for storing package metadata (POCO format in Model/PackageMetadata.cs)
2) Initial commit for the oss-metadata tool, which extracts metadata for the package and outputs the JSON format.
3) Update the C# version of all projects to 9
4) Implement the NPM provider for the package …
=> Add OSS Metadata Tool

src/Shared/PackageManagers/NuGetProjectManager.cs, src/oss-characteristics/CharacteristicTool.cs, src/oss-defog/DefoggerTool.cs, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-metadata/oss-metadata.csproj, src/oss-tests/DownloadTests.cs, src/oss-tests/FindSourceTests.cs
This PR fixes an issue related how to VSM files are pulled down. Since they include non-archive files, our assumptions failed, so this PR handles both directories and plain files.
This PR also fixes a minor bug in the find-source tool, which assumed that the same URL would only be found once on a page.
=> Fixes #187 and #186.

src/OSSGadget.sln, src/oss-find-domain-squats/FindDomainSquatsTool.cs, src/oss-find-domain-squats/oss-find-domain-squats.csproj, src/oss-find-squats/FindSquatsTool.cs, src/oss-find-squats/Generative.cs, src/oss-find-squats/oss-find-squats.csproj, src/oss-tests/FindSquatsTests.cs, src/oss-tests/oss-tests.csproj
Checks all the typo/bitflip squats for a given domain name "i.e. microsoft.com".  Separates results into three categories.
1. Domains Registered to the same organization
2. Domains registered to other organizations
3. Domains not registered
Future work: currently I'm passing tuples, we could change those to be richer objects which contain more metadata about each whois.
=> Add oss-find-domain-squats

Pipelines/core-pipeline.yml, Pipelines/templates/dotnet-publish-linux-mac-job.yml, Pipelines/templates/dotnet-publish-win-netcore-job.yml, Pipelines/templates/dotnet-test-job.yml, src/Shared/Shared.csproj, src/oss-characteristics/oss-characteristic.csproj, src/oss-defog/oss-defog.csproj, src/oss-detect-backdoor/oss-detect-backdoor.csproj, src/oss-detect-cryptography/oss-detect-cryptography.csproj, src/oss-diff/oss-diff.csproj, src/oss-download/oss-download.csproj, src/oss-find-domain-squats/oss-find-domain-squats.csproj, src/oss-find-source/oss-find-source.csproj, src/oss-find-squats/oss-find-squats.csproj, src/oss-health/oss-health.csproj, src/oss-metadata/oss-metadata.csproj, src/oss-risk-calculator/oss-risk-calculator.csproj, src/oss-tests/oss-tests.csproj
This PR adds RuntimeIdentifiers to each project to enable self-contained cross-project publishing.
From [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish):
> --self-contained [true|false]
> 
> Publishes the .NET runtime with your application so the runtime doesn't need to be installed on the target machine. Default is true if a runtime identifier is specified and the project is an executable project (not a library project). For more information, see .NET application publishing and Publish .NET apps with the .NET CLI.
> 
More information in [dotnet/sdk#10902](https://github.com/dotnet/sdk/issues/10902).
This should fix #213.
=> Add RuntimeIdentifiers to each project.

src/oss-find-squats/Generative.cs
I might be wrong, but it seems there is a mistake here.
The algorithm swaps `arg[i]` and `arg[i +1]`, but the first part of the resulting string is always missing a letter. I.e. it should be of length `i` not `i - 1`. Correct me if I'm wrong.
Please find examples below.
`lodash`
```
doash ["letter swapped"]
ladsh ["letter swapped"]
losah ["letter swapped"]
lodhs ["letter swapped"]
```
`react-dom`
```
aect-dom ["letter swapped"]
rcat-dom ["letter swapped"]
retc-dom ["letter swapped"]
rea-tdom ["letter swapped"]
reacd-om ["letter swapped"]
reactodm ["letter swapped"]
react-mo ["letter swapped"]
```
`lodash`
```
ldoash ["letter swapped"]
loadsh ["letter swapped"]
lodsah ["letter swapped"]
lodahs ["letter swapped"]
```
`react-dom`
```
raect-dom ["letter swapped"]
recat-dom ["letter swapped"] …
```
=> Fix _swapOrderOfLetters to not lose a letter

src/oss-diff/DiffTool.cs, src/oss-find-source/FindSourceTool.cs
Previous show all option was not honored and was the default.
This keeps the same default behavior but adds a single output option.
=> Adds Single Option

src/oss-defog/DefoggerTool.cs
Java classfile magic is `CAFEBABE`, not `CAFEBEBE`. See https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.1.
=> Fix Java classfile magic

.dockerignore, Dockerfile
This will allow a user to run a command with something as simple as `oss-download` instead of `./oss-download/bin/Debug/net5.0/oss-download`.
The [wiki page](https://github.com/microsoft/OSSGadget/wiki/Docker-Image) will also need updated to match. I suggest also adding `--rm` to the `run` command. Plus `latest` is the default anyway, so the command could just be ` docker run --rm -it ossgadget` (same as `build`, as far as that goes, i.e. ` docker build -t ossgadget .`).
=> Make commands easier to run in Docker

src/Shared/Helpers/OutputBuilder/SarifOutputBuilder.cs, src/Shared/OSSGadget.cs, src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/MavenProjectManager.cs, src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/Shared/Shared.csproj, src/oss-characteristics/CharacteristicTool.cs, src/oss-characteristics/oss-characteristic.csproj, src/oss-defog/DefoggerTool.cs, src/oss-defog/oss-defog.csproj, src/oss-detect-backdoor/oss-detect-backdoor.csproj, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-detect-cryptography/oss-detect-cryptography.csproj, src/oss-diff/oss-diff.csproj, src/oss-download/oss-download.csproj, src/oss-find-domain-squats/oss-find-domain-squats.csproj, src/oss-find-source/oss-find-source.csproj, src/oss-find-squats/oss-find-squats.csproj, src/oss-health/oss-health.csproj, src/oss-metadata/oss-metadata.csproj, src/oss-reproducible/ReproducibleTool.cs, src/oss-reproducible/oss-reproducible.csproj, src/oss-risk-calculator/oss-risk-calculator.csproj, src/oss-tests/DetectCryptographyTests.cs, src/oss-tests/oss-tests.csproj
This PR has two changes:
- When we accept an output filename, we check to see if it contains invalid chars, and if so, we write to the console instead. (Perhaps we should just error out?). In any case, if the user provides a full path, those slashes cause that check to fail, and the output goes to the screen. This PR fixes that.
- Change banner to stderr (from stdout) - This way, for sarif output (or text for that matter), redirecting can work too.
=> Fix #245 (output to console on full path)

src/Shared/nlog.config, src/oss-characteristics/CharacteristicTool.cs, src/oss-detect-backdoor/DetectBackdoorTool.cs, src/oss-detect-backdoor/Resources/BackdoorRules/backdoor_signatures.json, src/oss-detect-backdoor/Resources/BackdoorRules/code_execution.json, src/oss-detect-backdoor/Resources/BackdoorRules/data_exfiltration.json, src/oss-detect-backdoor/Resources/BackdoorRules/dependency_confusion.json, src/oss-detect-backdoor/Resources/BackdoorRules/ioc.json, src/oss-detect-backdoor/Resources/BackdoorRules/lolbas.json, src/oss-detect-backdoor/Resources/BackdoorRules/obfuscation.json, src/oss-detect-backdoor/Resources/BackdoorRules/pastebin.json, src/oss-detect-backdoor/Resources/BackdoorRules/reverse_shell.json, src/oss-detect-backdoor/oss-detect-backdoor.csproj
This PR improves some of the backdoor detection rules, as well as #253 which was causing us to come back with empty results. A few other tweaks too.
=> OSS Detect Backdoor Improvements

src/Shared/PackageManagers/GitHubProjectManager.cs, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-detect-cryptography/Resources/CryptographyRules/implementation-crypto-generic.json, src/oss-detect-cryptography/Resources/CryptographyRules/reference-common.json
This PR improves the oss-detect-cryptography tool in a few days:
First, output is cleaner (run against `pkg:npm/md5.js`):
Second, I added a bunch of common crypto libraries in various languages. This means that instead of only detecting implementations of crypto algorithms, we also detect calls to common libraries.
Added a few other bug fixes (like #256).
=> Add common crypto library references

Directory.Build.props, src/Shared/Shared.csproj, src/oss-characteristics/oss-characteristic.csproj, src/oss-defog/oss-defog.csproj, src/oss-detect-backdoor/oss-detect-backdoor.csproj, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-detect-cryptography/Issue.cs, src/oss-detect-cryptography/oss-detect-cryptography.csproj, src/oss-diff/oss-diff.csproj, src/oss-download/oss-download.csproj, src/oss-find-domain-squats/oss-find-domain-squats.csproj, src/oss-find-source/oss-find-source.csproj, src/oss-find-squats/oss-find-squats.csproj, src/oss-health/oss-health.csproj, src/oss-metadata/oss-metadata.csproj, src/oss-reproducible/oss-reproducible.csproj, src/oss-risk-calculator/oss-risk-calculator.csproj, src/oss-tests/DetectCryptographyTests.cs, src/oss-tests/oss-tests.csproj
Fix #260.
Removes all the extra references to NBGV. The Directory.Build.Props should handle it.
=> Converts OSS Detect Cryptography to use Application Inspector

src/Shared/Helpers/StringExtensions.cs, src/oss-find-squats-lib/MutateExtension.cs, src/oss-tests/FindSquatsTests.cs
For an npm package e.g. `@angular/core` the typo squats were generating mutations that were just variations on `core` returning things like `coree` and `cort`, etc. but for scoped npm packages we want the mutations to be more like `@engular/core` and `@angullar/core`. With the mutations on the scope/namespace, not the package name.
=> Added mutation support to the scope for scoped npm packages.

src/Shared.CLI/Shared.CLI.csproj, src/Shared/Model/PackageMetadata.cs, src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/GitHubProjectManager.cs, src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/Shared/Shared.Lib.csproj, src/Shared/Utilities/OssUtilities.cs
This PR aims to add some new features to the metadata tool.
It adds support for NuGet packages.
It adds a homepage property.
Fixes some bugs with NPM package parsing.
Adds a unique value for the frontend package and package version urls and the api urls. ie https://www.nuget.org/packages/Newtonsoft.Json vs https://api.nuget.org/v3/registration5-gz-semver2/newtonsoft.json/index.json
=> Update Metadata Normalization

src/Shared/Extensions/PackageUrlExtension.cs, src/Shared/OssGadgetJsonSerializer.cs, src/oss-find-squats-lib/FindPackageSquatResult.cs, src/oss-find-squats-lib/MutateExtension.cs, src/oss-tests/FindSquatsTests.cs
The new OssGadgetJsonSerializer contains the serialzer options needed for serializing and deserializing PackageURL objects.
Also fixed some issues with scoped npm packages and find squat mutations.
=> Added a static OssGadgetJsonSerializer class

src/oss-health/BaseHealthAlgorithm.cs
oss-health was continually complaining about GITHUB_ACCESS_TOKEN being
unset.  This was because [this previous commit](https://github.com/microsoft/OSSGadget/commit/a25747d039cc532a2ffc3e652474545e8527d10b) removed the call which allowed oss-health to set it from the
environment.  This commit restores that ability.
=> Allows oss-health to access GITHUB_ACCESS_TOKEN

src/Shared.CLI/Helpers/PackageDownloader.cs, src/Shared/Helpers/ArchiveHelper.cs, src/Shared/Model/PackageMetadata.cs, src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/CPANProjectManager.cs, src/Shared/PackageManagers/CRANProjectManager.cs, src/Shared/PackageManagers/CargoProjectManager.cs, src/Shared/PackageManagers/CocoapodsProjectManager.cs, src/Shared/PackageManagers/ComposerProjectManager.cs, src/Shared/PackageManagers/GemProjectManager.cs, src/Shared/PackageManagers/GitHubProjectManager.cs, src/Shared/PackageManagers/GolangProjectManager.cs, src/Shared/PackageManagers/HackageProjectManager.cs, src/Shared/PackageManagers/MavenProjectManager.cs, src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/Shared/PackageManagers/ProjectManagerFactory.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/Shared/PackageManagers/URLProjectManager.cs, src/Shared/PackageManagers/UbuntuProjectManager.cs, src/Shared/PackageManagers/VSMProjectManager.cs, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-download/Properties/launchSettings.json, src/oss-find-squats-lib/Mutators/IMutator.cs, src/oss-tests/ArchiveHelperTests.cs, src/oss-tests/FindSquatsTests.cs
A lot of this work comes from work I had done in #318 that I just wanted to separate out to make that PR easier to review.
This PR includes:
- Refactor `ExtractArchive` from `BaseProjectManager` into a separate `ArchiveHelper` static class.
- Rename `PackageManagerFactory` to `ProjectManagerFactory`, and remove the `BaseProjectManager` constructors as they were able to be removed thanks to the `ExtractArchive` change detailed above.
- Updated `PackageMetadata.User` to be a record instead of a class, will help with future json parsing.
- Made `BaseProjectManager` abstract.
- Add a `Type` readonly string to each implementation of `BaseProjectManager`. Isn't currently being used as of this PR, but #318 uses it, and I anticipate it being useful in other places in the future as well.
- Add …
=> Refactor ExtractArchive into a helper class, and a few other changes.

src/Shared.CLI/Helpers/OutputBuilder/SarifOutputBuilder.cs, src/Shared.CLI/Helpers/PackageDownloader.cs, src/Shared.CLI/Helpers/RepoSearch.cs, src/Shared.CLI/OSSGadget.cs, src/Shared/OssGadgetLib.cs, src/Shared/PackageManagers/ProjectManagerFactory.cs, src/oss-characteristics/CharacteristicTool.cs, src/oss-defog/DefoggerTool.cs, src/oss-detect-backdoor/DetectBackdoorTool.cs, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-diff/DiffTool.cs, src/oss-download/DownloadTool.cs, src/oss-find-domain-squats/FindDomainSquatsTool.cs, src/oss-find-source/FindSourceTool.cs, src/oss-find-squats-lib/FindPackageSquats.cs, src/oss-find-squats/FindSquatsTool.cs, src/oss-health/HealthMetrics.cs, src/oss-health/HealthTool.cs, src/oss-metadata/MetadataTool.cs, src/oss-reproducible/ReproducibleTool.cs, src/oss-risk-calculator/RiskCalculatorTool.cs, src/oss-tests/DownloadTests.cs, src/oss-tests/FindSourceTests.cs, src/oss-tests/FindSquatsTests.cs, src/oss-tests/ProjectManagerTests/ProjectManagerFactoryTests.cs, src/oss-tests/SharedTests.cs
Refactor the ProjectManagerFactory to no longer use reflection for the construction of ProjectManagers.
Switch OSSGadgetLib to use a ProjectManagerFactory instead of an IHttpClientFactory, and make the change in OSSGadget as well.
=> Refactor the ProjectManagerFactory

src/Shared/Model/PackageMetadata.cs, src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/oss-tests/ProjectManagerTests/NPMProjectManagerTests.cs, src/oss-tests/ProjectManagerTests/NuGetProjectManagerTests.cs, src/oss-tests/ProjectManagerTests/PyPIProjectManagerTests.cs
It returns the DateTime of a given purl (with a specified version) for when it was published. Or returns null if it couldn't be found.
For CFS we are using this data, so having a direct method to get it vs calling GetPackageMetadata and only keeping the time would help. If you disagree no worries and we can just do that, this was just a fairly easy thing to whip up.
Also, `NPMProjectManager` wasn't setting `UploadTime` in the `GetPackageMetadata` call.
=> Add GetPublishedAtAsync to BaseProjectManager

.gitignore, PRIVACY.md, README.md, src/Shared.CLI/OSSGadget.cs, src/Shared/Metadata/BaseMetadataSource.cs, src/Shared/Metadata/DepsDevMetadataSource.cs, src/Shared/Metadata/LibrariesIoMetadataSource.cs, src/Shared/Metadata/NativeMetadataSource.cs, src/Shared/nlog.config, src/oss-metadata/MetadataTool.cs, src/oss-metadata/oss-metadata.csproj, src/oss-reproducible/ReproducibleTool.cs, src/oss-tests/MetadataTests.cs, src/oss-tests/oss-tests.csproj
Fixes #335 
This PR adds support for querying the deps.dev API (unauthenticated) and libraries.io (unauthenticated or authenticated via a user-supplied API token). The results are serialized (JSON) and written to the console.
=> Refactor metadata tool to use deps.dev and libraries.io

src/Shared/PackageManagers/PyPIProjectManager.cs, src/oss-tests/FindSourceTests.cs
This PR updates the logic to identify source repos within PyPI. Instead of just checking for "project_urls.source", we have a list of keys and look through each one.
It's necessary because prior versions failed on pypi/jslint.
=> Check additional fields in PyPI metadata for source repo.

src/Shared/Contracts/IPackageExistence.cs, src/Shared/Model/PackageExistence/PackageExistence.cs, src/Shared/Model/PackageExistence/PackageVersionExistence.cs, src/Shared/PackageManagers/CPANProjectManager.cs, src/Shared/PackageManagers/CRANProjectManager.cs, src/Shared/PackageManagers/CargoProjectManager.cs, src/Shared/PackageManagers/CocoapodsProjectManager.cs, src/Shared/PackageManagers/ComposerProjectManager.cs, src/Shared/PackageManagers/GemProjectManager.cs, src/Shared/PackageManagers/GitHubProjectManager.cs, src/Shared/PackageManagers/GolangProjectManager.cs, src/Shared/PackageManagers/HackageProjectManager.cs, src/Shared/PackageManagers/MavenProjectManager.cs, src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/Shared/PackageManagers/UbuntuProjectManager.cs, src/Shared/PackageManagers/VSMProjectManager.cs, src/oss-tests/ProjectManagerTests/NuGetProjectManagerTests.cs, src/oss-tests/ProjectManagerTests/PyPIProjectManagerTests.cs
I noticed when implementing version 0.1.346 of OSSGadget that our unit tests for package versions that don't exist would fail, as 
`var packageVersionExistence = await projectManager.DetailedPackageVersionExistsAsync(purl);` would throw an `HttpRequestException` where the `StatusCode` is `HttpStatusCode.NotFound`.
I would expect this case to return a `PackageVersionNotFound` instance of `IPackageExistence` instead of throwing a 404.
This PR adds:
``` cs
catch (HttpRequestException ex) when (ex.StatusCode == HttpStatusCode.NotFound)
{
Logger.Debug("Unable to enumerate versions (404): {0}", ex.Message);
return Array.Empty<string>();
}
```
to each `ProjectManager`'s implementation of `EnumerateVersionsAsync`.
=> Fix issues with EnumerateVersionsAsync not handling 404s

src/Shared/Contracts/IPackageExistence.cs, src/Shared/Model/PackageExistence/PackageExistence.cs, src/Shared/Model/PackageExistence/PackageVersionExistence.cs, src/oss-tests/PackageExistenceTests.cs, src/oss-tests/ProjectManagerTests/NPMProjectManagerTests.cs
Remove HasEverExisted and WasRemoved flags from IPackageExistence as we can't be sure those values are correct as the registries aren't 100% immutable. We can't guarantee that HasEverExisted would be correct in those cases.
ex: this package [@softvisio/webview](https://registry.npmjs.org/@softvisio/webview) did exist, but now 404s.
=> Remove HasEverExisted and WasRemoved flags from IPackageExistence

Pipelines/templates/dotnet-build-publish-all-platforms-job.yml
Removes the extra build and restore steps from the publish all platforms pipeline.
Fix #340
=> Fix self-contained warning

src/Shared.CLI/Shared.CLI.csproj, src/Shared/PackageActions/NuGetPackageActions.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/Shared/Shared.Lib.csproj, src/oss-tests/ProjectManagerTests/NuGetProjectManagerTests.cs
Package versions in NuGet are case insensitive, and NuGet's GET package versions API returns a list of all package versions in lowercase. OSSGadget's NuGetProjectManager should lowercase a package version before comparing it against the returned list of package versions.
=> Nuget package versions are case insensitive

Directory.Build.props, src/Shared.CLI/Shared.CLI.csproj, src/Shared/Shared.Lib.csproj, src/oss-characteristics/CharacteristicTool.cs, src/oss-characteristics/oss-characteristic.csproj, src/oss-detect-cryptography/DetectCryptographyTool.cs, src/oss-detect-cryptography/oss-detect-cryptography.csproj, src/oss-diff/oss-diff.csproj, src/oss-find-domain-squats/oss-find-domain-squats.csproj, src/oss-find-source/oss-find-source.csproj, src/oss-find-squats/oss-find-squats.csproj, src/oss-health/oss-health.csproj, src/oss-metadata/oss-metadata.csproj, src/oss-reproducible/oss-reproducible.csproj, src/oss-tests/DetectCryptographyTests.cs, src/oss-tests/MetadataTests.cs, src/oss-tests/oss-tests.csproj
The previous target did a large refactor where they now call into the WASM implementation of Blake3. Switching the target for the test to be the cargo for that implementation.
=> Fix Detect Blake3 Test

src/Shared/DefaultHttpClientFactory.cs, src/Shared/Helpers/ArchiveHelper.cs, src/Shared/PackageManagers/CocoapodsProjectManager.cs
This PR fixes a few issued identified by CodeQL:
* We didn't explicitly have certificate revocation checking enabled when connecting to endpoints.
* The justification for a small StringBuilder modifying loop was not recognized correctly.
* The justification for using MD5 as part of the CocoaPods path sharding sheme wasn't suppressed.
=> Add revocation checking, tweaked suppressions.

src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/MavenProjectManager.cs, src/oss-tests/DownloadTests.cs
This change adds environment variable overrides for package managers. The [wiki documentation](https://github.com/microsoft/OSSGadget/wiki/Advanced-Usage) implies that this works for tools like `oss-download` by adding a `MAVEN_ENDPOINT` environment variable, but the code did not support it.
Additionally, there is a change to the Maven package manager to download jars that do not have javadoc or source jars available. Previously, if one or both jars were missing the actual jar would not be downloaded as an exception was encountered and the loop exited early
=> Support environment variable overrides in package managers

src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/Shared/PackageManagers/TypedManager.cs
This pull request moves the implementation for GetArtifactDownloadUris to the TypedManager class since all of the implementations were the same.  It also switches from using .Result to use .GetAwaiter().GetResult() for the sync-to-async call to avoid issues with deadlocks.
=> Cleanup the GetArtifactDownloadUris to instead be returned from the TypedManager class

Pipelines/templates/nuget-build-job.yml
The build is currently failing to build NuGet packages on the code signing step due to a missing .NET SDK.  This change adds in that missing SDK prior to the code signing.
=> Add missing SDK for NuGet builds

src/oss-detect-backdoor/Resources/BackdoorRules/dependency_confusion.json
Simple change, just modifies a regex used to detect certain backdoors. Turns out, the period prefix isn't needed.
Signed-off-by: Michael Scovetta <michael.scovetta@microsoft.com>
=> Remove extra dot in suspicious hostname check.

src/Shared.CLI/Helpers/PackageDownloader.cs, src/Shared/Helpers/ArchiveHelper.cs, src/oss-detect-cryptography/DetectCryptographyTool.cs
=> Directory issues, print package name, fix options output

src/Shared/Shared.Lib.csproj
This pull request updates the PackageURL dependency to version 1.2.0.  This version incorporates updates to how package names are normalized, so as to better handle package managers that allow for case-sensitive packages.
=> Update to PackageUrl 1.2.0

src/oss-find-squats-lib/MutateExtension.cs, src/oss-find-squats-lib/Mutators/CloseLettersMutator.cs, src/oss-find-squats-lib/Mutators/SubstitutionMutator.cs, src/oss-find-squats-lib/Mutators/SwapOrderOfLettersMutator.cs, src/oss-tests/FindSquatsTests.cs
- Add a few more prefixes and suffixes for npm.
- Add substitution and suffix mutators for PyPi.
- Update the close letters mutator to add a close letter to the end of a string. We missed the node package sqliter from sqlite as a typosquat. 
- Fix substitution mutator.
- Fix Swap Order Of Letters mutator.
- Update FindSquatsTests.
=> Fix some issues with the squat mutators

src/oss-tests/Properties/Resources.resx
Fix #392. 
Linux file system treats file and directory names as case-sensitive. One path name in `src/oss-tests/Properties/Resources.resx` is not case-sensitive, leading to Docker build failures in Linux environments. This PR fixes this path name
=> Fix Docker build failures in Linux environments.

src/oss-find-squats-lib/MutateExtension.cs, src/oss-find-squats-lib/Mutators/DuplicatorMutator.cs
- Remove `SeparatorRemovedMutator` from the list of `BaseMutators` as it was causing problems and usually doesn't catch squats. Squats that would be caught by it are also caught by the prefix or suffix mutator.
- Overrode the `SeparatorChangedMutator` for PyPi as PyPi considers `-` and `_` to be the same character. So just removed `_` from the list. There might be a better way of doing this, but I haven't thought of one yet.
- Fixed issues with the `DuplicatorMutator` that was giving the original name back as a mutated one.
=> Update squat logic to address bugs.

src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/PyPIProjectManager.cs
Fix #398 
Currently, oss-find-source only searches properties with certain keys in the `project_urls` filed. But it is possible that other properties (e.g., the `Download` property in tensorflow package's metadata) also contain source code repository information.
=> Improve oss-find-source for PyPI packages.

src/oss-find-squats-lib/MutateExtension.cs, src/oss-find-squats-lib/MutateOptions.cs, src/oss-find-squats-lib/Mutators/MutatorType.cs, src/oss-find-squats-lib/Mutators/NamespaceInNameMutator.cs, src/oss-tests/FindSquatsTests.cs
- Add a field to `MutateOptions` called `ExcludedMutators` that is of type `IEnumerable<MutatorType>?` which will exclude a given `MutatorType` from being used when generating mutations.
- We needed this for the way we are generating mutations, we don't want the `RemoveNamespaceMutator` for our use case, but I don't want to remove it from the base mutators.
- Added a new mutator `NamespaceInNameMutator` that performs a mutation to move the namespace to the name.
- Example: Given `pkg:npm/%40angular/core`
- `pkg:npm/angular-core`
- `pkg:npm/angular.core`
- `pkg:npm/angular_core`
- `pkg:npm/angularcore`
=> Add the ability to exclude mutators, and added a new NamespaceInName mutator.

src/oss-find-squats-lib/MutateExtension.cs, src/oss-find-squats-lib/Mutators/IMutator.cs, src/oss-find-squats-lib/Mutators/PrefixMutator.cs, src/oss-tests/FindSquatsTests.cs
- Readd `RemoveSeparatedSectionMutator` to the list of defaults, but remove it specifically for NPM.
- Fix issues where mutations would be just a separator. EX: `pkg:npm/q` would make `pkg:npm/.` or `pkg:npm/typescript` could make `pkg:npm/-`
- Fix bug with scoped npm packages with the prefix mutator would add before the `@` resulting in mutations like `pkg:npm/-%40types/node` when that isn't possible. It now adds after the `@` but before the namespace begins, resulting in `pkg:npm/%40-types/node`
=> Fix some bugs

src/Shared/PackageManagers/MavenProjectManager.cs
It makes the check for version existence much more efficient by not parsing through all of the package versions.
=> Update MavenProjectManager to override the PackageVersionExistsAsync method

src/oss-find-squats-lib/MutateExtension.cs, src/oss-find-squats-lib/Mutators/AddContainingCharacterMutator.cs, src/oss-find-squats-lib/Mutators/MutatorType.cs, src/oss-tests/FindSquatsTests.cs
This new mutator was added to help with scenarios of going from squat candidate, to popular package name, and then confirming that said squat candidate is a squat on the popular package.
Example being, without the AddCharacterMutator, pkg:pypi/reuquests would not be a squat on pkg:pypi/requests, this mutator adds that ability without adding too much noise such as saying pkg:pypi/requestsn is also a squat on pkg:pypi/requests
=> Add new AddContainingCharacterMutator

src/Shared/PackageManagers/NuGetProjectManager.cs, src/oss-tests/ProjectManagerTests/NuGetProjectManagerTests.cs
"PackageVersionExistsAsync" and "GetArtifactDownloadUris"  methods return incorrect response when a package version with metadata is requested. This happens as the version string is not normalized as per NuGet standards when creating a download URL. Fixed the logic to parse nuget version using NuGet SDK.
=> Parse nuget version to exclude metadata when creating package URL's

src/Shared/PackageManagers/GitHubProjectManager.cs
Adds reasonable limits on length of matches for various components of the github url.
=> Add character limits for GitHub repo detection Regex

src/Shared/Contracts/IBaseProjectManager.cs, src/Shared/Contracts/IProjectManagerFactory.cs, src/Shared/Contracts/ITypedManager.cs, src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/ProjectManagerFactory.cs, src/Shared/PackageManagers/TypedManager.cs
Adds IProjectManagerFactory.cs, IBaseProjectManager, ITypedManager interfaces, such that consuming projects can mock ProjectManagerFactory, BaseProjectManager, and TypedManager using tools like `FakeItEasy` or `Moq`.
=> Add interfaces enabling consuming projects to mock ProjectManagerFactory, BaseProjectManager, and TypedManager

src/Shared.CLI/Helpers/OutputBuilder/SarifOutputBuilder.cs, src/Shared.CLI/Helpers/PackageDownloader.cs, src/Shared.CLI/Helpers/RepoSearch.cs, src/Shared/Contracts/IProjectManagerFactory.cs, src/Shared/PackageManagers/ProjectManagerFactory.cs, src/oss-diff/DiffTool.cs, src/oss-find-squats-lib/FindPackageSquats.cs, src/oss-find-squats-lib/MutateExtension.cs, src/oss-health/HealthMetrics.cs, src/oss-health/HealthTool.cs, src/oss-tests/DownloadTests.cs, src/oss-tests/FindSquatsTests.cs, src/oss-tests/ProjectManagerTests/ProjectManagerFactoryTests.cs, src/oss-tests/SharedTests.cs
As part of #416 , I neglected to make `IProjectManagerFactory` return `IBaseProjectManager` such that mocked instances of `IBaseProjectManager` could be returned to users of `IProjectManagerFactory`.
This change corrects that omission, and updates all uses of `ProjectManagerFactory` to receive `IBaseProjectManager` instead.
=> IProjectManagerFactory now returns IBaseProjectManager instead of BaseProjectManager

src/Shared/DefaultHttpClientFactory.cs, src/Shared/Helpers/EnvironmentHelper.cs, src/Shared/Metadata/BaseMetadataSource.cs, src/Shared/Metadata/DepsDevMetadataSource.cs, src/Shared/Metadata/LibrariesIoMetadataSource.cs, src/Shared/OssGadgetLib.cs, src/Shared/PackageManagers/CPANProjectManager.cs, src/Shared/PackageManagers/CRANProjectManager.cs, src/Shared/PackageManagers/CargoProjectManager.cs, src/Shared/PackageManagers/CocoapodsProjectManager.cs, src/Shared/PackageManagers/ComposerProjectManager.cs, src/Shared/PackageManagers/GemProjectManager.cs, src/Shared/PackageManagers/GitHubProjectManager.cs, src/Shared/PackageManagers/GolangProjectManager.cs, src/Shared/PackageManagers/HackageProjectManager.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/Shared/PackageManagers/UbuntuProjectManager.cs, src/Shared/PackageManagers/VSMProjectManager.cs, src/oss-health/GitHubHealthAlgorithm.cs
Search for static and non public members as well when overriding values. Here's how the member is defined in GitHubHealthAlgorithm.cs:
private static string? ENV_GITHUB_ACCESS_TOKEN = null;
Searching for public members only misses it and it's never set from the environment variable.
I don't know if this is the right way to fix this, but at least it get's me one step further and I can actually run the oss-health tool for an npm project.
=> Fix environment variable processing. (#406)

src/Shared.CLI/OSSGadget.cs
For some reason, I typo'ed npmjs.com to npm.org in the help screen for OSS Gadget. This PR fixes that text.
Fixes part of #418.
=> Fix typo (npm.org -> npmjs.com)

src/oss-reproducible/README.md, src/oss-reproducible/ReproducibleTool.cs
Based on feedback in #422 update the readme to distinguish between a [Reproducible Build](https://en.wikipedia.org/wiki/Reproducible_builds) and OSS Reproducible's likelihood strategies.
=> Update Reproduciblity Readme

src/Shared/Shared.Lib.csproj, src/oss-find-squats-lib/Mutators/IMutator.cs
I have updated the package-url dotnet library to handle the special characters in the purl components (name, namespace, version, subpath and qualifiers) as per the PURL spec. As part of that change, the PackageUrl now accepts unencoded PURL components and it takes care of encoding/unencoding them when parsing/generating the PURL.  Here is the[ PR](https://github.com/package-url/packageurl-dotnet/pull/23) that has these changes.
I have updated the OSSGadget to use the new dotnet PURL library, as per the new updates, PackageURL constructor now accepts unencoded Purl components as arguments.
=> Updated packageurl-dotnet library.

src/oss-tests/ProjectManagerTests/NuGetProjectManagerTests.cs
In my previous PR I have updated the dotnet package-url library to the latest version that includes the changes to proper encoding/decoding the PURL. As per the[ PURL spec](https://github.com/package-url/purl-spec/blob/c02b002f09bdc88a501f62259eec18761957828a/PURL-SPECIFICATION.rst#how-to-build-purl-string-from-its-components), the special characters in the namespace, name, version, subpath etc. should be properly encoded in a purl string. 
I missed running few tests locally as my fork repo wasn't updated with the upstream, and the tests are failing as the purl string is not properly encoded. In this PR, I have a fix for the failed tests to have properly encoded purl strings as inputs.
The nuget versions containing special characters "+" in the version are encoded in the purl string.
=> Encoded version string the purl string.

src/Shared.CLI/Shared.CLI.csproj, src/Shared/Shared.Lib.csproj
Earlier today I merged a Dependabot PR which created version conflicts. This attempts to properly update all the Nuget packages to the latest version so they match again.
=> Fix Dependabot's Version update

src/Shared/PackageManagers/NPMProjectManager.cs, src/oss-download/DownloadTool.cs
Also fix #420 - auto escape namespaces with @ in the first character of a namespace in the oss-download cli.
=> Fix Npm Project Manager's Download Version Async respecting namespaces

src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/oss-tests/ProjectManagerTests/PyPIProjectManagerTests.cs
Current implementation of "GetPublishedAtUtcAsync" is fetching all the metadata for a given package version, which is causing significant delay. To improve the latency, optimized "GetPublishedAtUtcAsync" method to fetch the uploadtime alone.
=> Improved "GetPublishedAtUtcAsync" method efficiency

src/Shared/PackageManagers/CocoapodsProjectManager.cs, src/oss-tests/DownloadTests.cs
=> Fix cocoapods version enumeration

src/Shared/PackageManagers/BaseProjectManager.cs
1) Set cache entry size to the content length of the http response received.
2) Set cache expiration for a cache entry.
3) Set different cache keys for jsonDoc cache entry and http string response cache entry
=> Add cache expiration for HttpCache entries.

src/oss-tests/FindSourceTests.cs, src/oss-tests/oss-tests.csproj
Per #441, interim commit to lock moq version to 4.18.2 until we decide on a path forward.
=> Lock moq version to 4.18.2

Pipelines/templates/dotnet-build-publish-all-platforms-job.yml, Pipelines/templates/dotnet-test-job.yml, Pipelines/templates/nuget-build-job.yml, src/Shared.CLI/Shared.CLI.csproj, src/Shared/Shared.Lib.csproj, src/oss-characteristics/CharacteristicTool.cs, src/oss-characteristics/oss-characteristic.csproj, src/oss-defog/oss-defog.csproj, src/oss-detect-backdoor/DetectBackdoorTool.cs, src/oss-detect-backdoor/oss-detect-backdoor.csproj, src/oss-detect-cryptography/oss-detect-cryptography.csproj, src/oss-diff/oss-diff.csproj, src/oss-download/oss-download.csproj, src/oss-find-domain-squats/oss-find-domain-squats.csproj, src/oss-find-source/oss-find-source.csproj, src/oss-find-squats-lib/oss-find-squats-lib.csproj, src/oss-find-squats/oss-find-squats.csproj, src/oss-fresh/oss-fresh.csproj, src/oss-health/oss-health.csproj, src/oss-metadata/oss-metadata.csproj, src/oss-reproducible/oss-reproducible.csproj, src/oss-risk-calculator/oss-risk-calculator.csproj, src/oss-tests/oss-tests.csproj
Build zipped tools with .NET 8.
Target Nugets for .NET 6 and .NET 8
Update dependencies
Fix #452
=> Add "EnableNonBacktrackingRegex" option to oss-characteristic tool

Pipelines/templates/dotnet-test-job.yml, src/oss-tests/ProjectManagerTests/GolangProjectManagerTests.cs
Intended as temporary workaround for #455. The test suceeds locally but fails in the pipeline. Also update test pipeline to install both net 6 and net 8 sdks so tests can be run for both frameworks.
=> Ignore test that fails in pipeline

Pipelines/core-pipeline.yml
We are hitting errors when trying to publish github releases, try switching to a newly created service connection.
=> Switch to newly created service connection

src/Shared/PackageManagers/CargoProjectManager.cs, src/oss-tests/ProjectManagerTests/CargoProjectManagerTests.cs
While investigating a spike of Cargo 500s, Terrapin has seen that periodically Cargo registry returns 500 error responses and OSS Gadget does not retry such requests. This change adds a retry mechanism for operations in Cargo project manager and accompanying unit tests for the changes.
=> Cargo project manager retry 500 errors.

src/Shared/Contracts/IBaseProjectManager.cs, src/Shared/Contracts/IProjectManagerFactory.cs, src/Shared/PackageManagers/BaseProjectManager.cs, src/Shared/PackageManagers/CPANProjectManager.cs, src/Shared/PackageManagers/CRANProjectManager.cs, src/Shared/PackageManagers/CargoProjectManager.cs, src/Shared/PackageManagers/CocoapodsProjectManager.cs, src/Shared/PackageManagers/ComposerProjectManager.cs, src/Shared/PackageManagers/CondaProjectManager.cs, src/Shared/PackageManagers/GemProjectManager.cs, src/Shared/PackageManagers/GitHubProjectManager.cs, src/Shared/PackageManagers/GolangProjectManager.cs, src/Shared/PackageManagers/HackageProjectManager.cs, src/Shared/PackageManagers/MavenProjectManager.cs, src/Shared/PackageManagers/NPMProjectManager.cs, src/Shared/PackageManagers/NuGetProjectManager.cs, src/Shared/PackageManagers/ProjectManagerFactory.cs, src/Shared/PackageManagers/PyPIProjectManager.cs, src/Shared/PackageManagers/TypedManager.cs, src/Shared/PackageManagers/URLProjectManager.cs, src/Shared/PackageManagers/UbuntuProjectManager.cs, src/Shared/PackageManagers/VSMProjectManager.cs, src/oss-tests/FindSquatsTests.cs, src/oss-tests/ProjectManagerTests/CondaProjectManagerTests.cs, src/oss-tests/ProjectManagerTests/GolangProjectManagerTests.cs, src/oss-tests/ProjectManagerTests/MavenProjectManagerTests.cs, src/oss-tests/ProjectManagerTests/NPMProjectManagerTests.cs, src/oss-tests/ProjectManagerTests/ProjectManagerFactoryTests.cs
On a previous incident occurring due to a disruption in npmjs.org, there were very long response times (~60s) that ultimately came back with 503 responses. This impacted Terrapin's latencies and availability. This change allows users to specify timeouts when they use OSSGadget's project managers when they call `CreateProjectManager`
=> Add optional timeouts for project managers

src/oss-gadget-cli/OssGadgetCli.cs
It looks like we missed the `MetadataTool` and `DetectBackdoorTool` options in the CLI. This PR just adds the references back.
=> Add missing MetadataTool and DetectBackdoorTool options in the CLI.
